# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 19:05
from __future__ import unicode_literals

from django.db import migrations

import csv


def rater_data(apps, schema_editor):
    Rater = apps.get_model("movie_app", "Rater")

    with open("u.user") as outfile:
        rater = csv.DictReader(outfile, fieldnames=["user_id", "age", "gender", "occupation", "zip_code"],
                               delimiter="|")

        for row in rater:
            Rater.objects.create(
                user_id=int(row['user_id']),
                age=int(row['age']),
                gender=row['gender'],
                occupation=row['occupation'],
                zip_code=row['zip_code']
            )

    # raise Exception('yay1')

class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rater_data)
        # migrations.RunPython(movie_data)
        # migrations.RunPython(ratings_data)

    ]
